#!/usr/bin/env python3
"""Three-way comparison aggregator: baseline / v2 / WTB-MAS.

Pulls metrics from each of the three result locations and produces:
  - A single side-by-side comparison JSON
  - A markdown summary table (slide-ready)
  - A CSV for plotting

Usage:
    python scripts/aggregate_three_way.py
    python scripts/aggregate_three_way.py --models qwen3:8b gemma4:31b
    python scripts/aggregate_three_way.py --output-dir Phase3_Report

Inputs (per model):
    score/{model}/Wild-Tool-Bench_metric.json              # baseline
    score_v2/{model}/Wild-Tool-Bench_metric.json           # eval-improvements
    score/wtbmas:{model}/Wild-Tool-Bench_metric.json       # WTB-MAS

Outputs (default to Phase3_Report/):
    three_way_comparison.json
    three_way_comparison.md
    three_way_comparison.csv
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from pathlib import Path

DEFAULT_MODELS = ["qwen3:8b", "qwen3:14b", "qwen3:32b", "gemma4:31b"]


def load_metric(path: str | os.PathLike) -> dict | None:
    p = Path(path)
    if not p.exists():
        return None
    try:
        with p.open() as f:
            return json.load(f)
    except Exception:  # noqa: BLE001
        return None


def extract(metric: dict | None) -> dict:
    """Pull the metrics we care about for the presentation."""
    if metric is None:
        return {}
    out: dict = {}
    total = metric.get("total_info", {})
    out["task_accuracy"] = total.get("task", {}).get("accuracy")
    out["task_correct"] = total.get("task", {}).get("correct_count")
    out["task_total"] = total.get("task", {}).get("total_count")
    out["session_accuracy"] = total.get("session", {}).get("accuracy")
    out["session_correct"] = total.get("session", {}).get("correct_count")
    out["session_total"] = total.get("session", {}).get("total_count")

    for k in ("Single-Tool", "Parallel Multi-Tool", "Sequential Multi-Tool",
              "Mixed Multi-Tool", "Clarify", "Chat"):
        info = metric.get("task_type_info", {}).get(k, {})
        out[f"{k}_accuracy"] = info.get("accuracy")

    for k in ("First Turn", "Coreferential Reference", "Partial Information",
              "Long-Range Dependency"):
        info = metric.get("turn_subtype_info", {}).get(k, {})
        out[f"{k}_accuracy"] = info.get("accuracy")
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--models", nargs="+", default=DEFAULT_MODELS)
    parser.add_argument("--output-dir", default="Phase3_Report")
    parser.add_argument("--repo-root", default=".",
                        help="Path to wild-tool-bench/ (where score/ and score_v2/ live)")
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    out_dir = root / args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    structured: dict[str, dict] = {}

    for model in args.models:
        # v1 = baseline, v2 = eval-improvements, v3 = WTB-MAS.
        # For v3 we prefer the canonical score_v3/ location; if that doesn't
        # exist (the chain hasn't yet symlinked it), we fall back to the raw
        # score/wtbmas:<model>/ path that the eval pipeline writes natively.
        v1 = load_metric(root / "score" / model / "Wild-Tool-Bench_metric.json")
        v2 = load_metric(root / "score_v2" / model / "Wild-Tool-Bench_metric.json")
        v3 = load_metric(root / "score_v3" / model / "Wild-Tool-Bench_metric.json")
        if v3 is None:
            v3 = load_metric(root / "score" / f"wtbmas:{model}" / "Wild-Tool-Bench_metric.json")

        b = extract(v1)
        v = extract(v2)
        m = extract(v3)

        structured[model] = {
            "v1_baseline": b,
            "v2_eval_improvements": v,
            "v3_wtbmas": m,
        }

        # Long-form rows for CSV / plotting
        for approach, data in (("v1_baseline", b), ("v2_eval_improvements", v), ("v3_wtbmas", m)):
            if not data:
                continue
            row = {"model": model, "approach": approach}
            row.update(data)
            rows.append(row)

    # ── JSON ─────────────────────────────────────────────
    json_path = out_dir / "three_way_comparison.json"
    with json_path.open("w") as f:
        json.dump(structured, f, indent=2)

    # ── CSV (long form) ─────────────────────────────────
    if rows:
        csv_path = out_dir / "three_way_comparison.csv"
        keys = sorted({k for r in rows for k in r.keys()})
        with csv_path.open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=keys)
            w.writeheader()
            for r in rows:
                w.writerow(r)

    # ── Markdown summary ────────────────────────────────
    md_lines = []
    md_lines.append("# Three-Way Comparison: Baseline · Eval-Improvements (v2) · WTB-MAS\n")
    md_lines.append("Auto-generated by `scripts/aggregate_three_way.py`.\n")

    md_lines.append("\n## Task accuracy (overall)\n")
    md_lines.append("| Model | v1 Baseline | v2 Eval-Improvements | v3 WTB-MAS | Δ v3 vs v1 |")
    md_lines.append("|-------|------------:|---------------------:|-----------:|-----------:|")
    for model in args.models:
        s = structured[model]
        bt = (s["v1_baseline"].get("task_accuracy") or 0) * 100
        vt = (s["v2_eval_improvements"].get("task_accuracy") or 0) * 100
        mt = (s["v3_wtbmas"].get("task_accuracy") or 0) * 100
        delta = mt - bt
        md_lines.append(f"| {model} | {bt:.1f}% | {vt:.1f}% | {mt:.1f}% | {delta:+.1f}pp |")

    md_lines.append("\n## Session accuracy (full 4-turn sessions correct)\n")
    md_lines.append("| Model | v1 Baseline | v2 Eval-Improvements | v3 WTB-MAS | Δ v3 vs v1 |")
    md_lines.append("|-------|------------:|---------------------:|-----------:|-----------:|")
    for model in args.models:
        s = structured[model]
        bs = (s["v1_baseline"].get("session_accuracy") or 0) * 100
        vs = (s["v2_eval_improvements"].get("session_accuracy") or 0) * 100
        ms = (s["v3_wtbmas"].get("session_accuracy") or 0) * 100
        delta = ms - bs
        md_lines.append(f"| {model} | {bs:.1f}% | {vs:.1f}% | {ms:.1f}% | {delta:+.1f}pp |")

    md_lines.append("\n## Per task-type (v3 WTB-MAS only)\n")
    md_lines.append("| Model | Single-Tool | Parallel | Sequential | Mixed | Clarify | Chat |")
    md_lines.append("|-------|------------:|---------:|-----------:|------:|--------:|-----:|")
    for model in args.models:
        m = structured[model]["v3_wtbmas"]
        if not m:
            md_lines.append(f"| {model} | — | — | — | — | — | — |")
            continue
        cells = [
            f"{(m.get('Single-Tool_accuracy') or 0)*100:.1f}%",
            f"{(m.get('Parallel Multi-Tool_accuracy') or 0)*100:.1f}%",
            f"{(m.get('Sequential Multi-Tool_accuracy') or 0)*100:.1f}%",
            f"{(m.get('Mixed Multi-Tool_accuracy') or 0)*100:.1f}%",
            f"{(m.get('Clarify_accuracy') or 0)*100:.1f}%",
            f"{(m.get('Chat_accuracy') or 0)*100:.1f}%",
        ]
        md_lines.append(f"| {model} | " + " | ".join(cells) + " |")

    md_path = out_dir / "three_way_comparison.md"
    md_path.write_text("\n".join(md_lines))

    print(f"Wrote: {json_path}")
    print(f"Wrote: {csv_path if rows else '(no CSV — empty rows)'}")
    print(f"Wrote: {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
